steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    dir: "public"
    args:
      [
        "-c",
        "gcloud app deploy app.yaml --quiet",
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY